import "./globals.css";

import type {Metadata} from "next";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import React from "react";
import {ThemeProvider} from "@mui/material/styles";
import theme from "@/theme";
import {AuthProviders} from "@/providers/AuthProviders";
import {NavBar} from "@/components/NavBar";
import {ReduxProvider} from "@/providers/ReduxProvider";
import {QueryProvider} from "@/providers/QueryProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {

    return (
        <html lang="en">
        <body>
        <QueryProvider>
            <ReduxProvider>
                <AuthProviders>
                    <AppRouterCacheProvider>
                        <ThemeProvider theme={theme}>
                            <NavBar/>
                            {children}
                        </ThemeProvider>
                    </AppRouterCacheProvider>
                </AuthProviders>
            </ReduxProvider>
        </QueryProvider>
        </body>
        </html>
    );
}
